version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: passwordtfm
      MYSQL_DATABASE: ctf
      MYSQL_USER: usertfm
      MYSQL_PASSWORD: passwordtfm

